dashM/urls.py
from django.urls import path
from . import views

app_name = "dashM"

urlpatterns = [
	path('', views.dashboard, name = 'manager'),
	path('accept/', views.task_accept_ajax, name='task_accept'),
	path('reject/', views.task_reject_ajax, name='task_reject'),
	path('delete/', views.task_delete_ajax, name='task_delete')
]

task/urls.py
from django.urls import path
from . import views

app_name = 'task'
urlpatterns = [
    path('employee/', views.show_task, name = 'employee'),
    path('add/', views.add_task, name='add_task'),
    path('employee/submit/<int:pk>', views.submit_task, name='submit_task')
]

tk1/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

from .views import index

# views
from team import views as team_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name = 'index'),
    path('login/',include('account.urls')),
    path('dashboard/', team_views.dashboard),
    # path('task/', include('task.urls')),
    path('', index, name = 'home'),
    path('teams/', team_views.dashboard, name='teams'),
    path('create-team/', team_views.create_team, name='create-team'),
    path('delete-team/<int:pk>/', team_views.delete_team, name='delete-team'),
    path('ajax-add-team/', team_views.add_team, name='ajax-add-team'),
    path('login/',include('account.urls', namespace='auth')),
    path('team/<int:id>/task/', include('task.urls', namespace="team")),
    path('team/<int:id>/chat/', include('chat.urls', namespace='chat')),
    path('dashM/<int:id>/', include('dashM.urls', namespace='manager'))
]

task/models.py
import sys
sys.path.append('..')
from team.models import Team

from django.db import models
# Models
from django.contrib.auth.models import User


# Create your models here.
class Task(models.Model):
    task_name = models.CharField(max_length = 100)
    description = models.TextField(max_length = 1000)
    member = models.ForeignKey(User, on_delete = models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, default=None)
    status = models.CharField(max_length = 50, default = 'on_going')

    # status = submitted --> sudah di submit menunggu di accept
    # status = accepted --> sudah di accept
    # status = on_going --> pas baru dikasih/abis di reject

    def __str__(self):
        return f'{self.task_name} is a task for {self.member}, task description : {self.description}'

task/forms.py
from django import forms
from .models import Task
from django.contrib.auth.models import User

from team.models import Team

class TaskForm(forms.Form):        
    task_name = forms.CharField(
        max_length = 100,
        widget = forms.TextInput(
            attrs={
                'class':'form-control-lg',
                'type' : 'text',
                'required': True,
                'autocomplete' : 'off',
                'placeholder' : 'Task Name',
            }
        )
    )

    description = forms.CharField (
        max_length = 1000,
        widget = forms.TextInput(
            attrs={
                'class':'form-control-lg',
                'type' : 'text',
                'autocomplete' : 'off',
                'required' : True,
            }
        )
    )

    member = forms.ModelChoiceField(
        queryset= Team.objects.all(),
        widget = forms.Select(
            attrs={
                'class':'form-control-lg',
                'required' : True,
            }
        )
    )

    def __init__(self, id, *args, **kwargs):
        self.id = kwargs.pop('id', None)
        super().__init__(*args, **kwargs)
        self.fields['member'].queryset = Team.objects.get(id=id).members.all()

task/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseBadRequest
from .models import Task
from .forms import TaskForm
from . import forms
from team.models import Team
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

# Create your views here.
@login_required(login_url="/login/")
def add_task(request, id) :
    task_form = forms.TaskForm(id)
    team_instance = Team.objects.get(id=id)
    members = team_instance.members.all()
    try :
        team = Team.objects.get(id=id)
    except Team.DoesNotExist :
        return HttpResponseBadRequest()
    
    if request.method == "POST":
        try :
            task_name = request.POST.get('task_name')
            description = request.POST.get('description')
            member = request.POST.get('member')
        except KeyError:
            return HttpResponseBadRequest
        
        try:
            member = User.objects.get(id=member)
        except:
            return HttpResponseBadRequest()

        task = Task(task_name = task_name, description = description, member = member, team = team)
        task.save()
        return JsonResponse({
            'success': True
        })
    else:
        current_data = Task.objects.filter(member=request.user).filter(status = 'on_going')
        return render(request, 'taskForm.html' ,{'form': task_form,'data':current_data, "team": team_instance, "member_list": members, 'team_id' : id })

@login_required(login_url="/login/")
def show_task(request, id) :
    task = Task.objects.filter(team = Team.objects.get(id=id)).filter(member=request.user).filter(status = 'on_going')
    team_instance = Team.objects.get(id=id)
    members = team_instance.members.all()
    response = {
        'tasks': task,
        "team": team_instance,
        "member_list": members,
        "team_id" : id,
    }
    return render(request,'employee.html', response)
    
@login_required(login_url="/login/")
def submit_task(request, id, pk) :
    if request.method == 'POST' :
        task = Task.objects.filter(team = Team.objects.get(id=id)).filter(member=request.user).get(id=pk)
        task.status = 'submitted'
        task.save()
        return redirect(f'/team/{id}/task/employee/')

task/templates/employee.html
{% extends 'base.html' %}
{% load static %}
{% block extra_headers %}
<link rel="stylesheet" href="{% static './task/task.css' %}">
{% endblock %}
{% block body %}
    <div class="content">
      <div class="members">
        <h1 class="team">{{team.name}}</h1>
        <div class="members-list">
          {% for member in member_list %}
          <div class="member">{{member.username|slice:"0:1"}}</div>
          {% endfor %}
        </div>
      </div>
      <hr>
      <br>
        <div class="container">
            <div style="width:100%; display:flex; justify-content: center;">
              <h3>My Tasks</h3>
            </div>
            {% if tasks|length == 0 %}
              <div style="display: flex; width: 100%; justify-content: center;">
                No Tasks
                <p style="font-size:20px; margin-left: .5em;">&#128512;</p>
              </div>
            {% endif %}
            <div >
              {% for t in tasks %}
              <form method ="POST" id = "form_task" action="{% url 'task:submit_task' id=team_id pk=t.id%}">
                  {% csrf_token %}
                  <div class="custom-control custom-checkbox mb-3">
                      <input type="submit" class="custom-control-input" id='{{t.id}}'>
                      <input type="hidden" value='{{t.id}}' name="task_id">
                      <label class="custom-control-label" for='{{t.id}}'> {{t.task_name}} </label>
                  </div>
                  <div class="listTask">
                      {{t.description}}
                  </div>
              </form>
            </div>
        <br>
    {% endfor %}
    </div>
{% endblock %}

task/templates/taskForm.html
{% extends 'base.html' %}
{% load static %}
{% block extra_headers %}
  <link rel="stylesheet" href="{% static './task/task.css' %}">
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
{% endblock %}

{% block body %}
    <div class="content">
      <div class="members">
        <h1 class="team">{{team.name}}</h1>
        <div class="members-list">
          {% for member in member_list %}
          <div class="member">{{member.username|slice:"0:1"}}</div>
          {% endfor %}
        </div>
      </div>
  <hr>
  <div class="container">
    <div class ="form">
      <form autocomplete="off" class="src-form" action="">
        {% csrf_token %}
        <div class="form-group" id ="form_task">
            <input type="text" class ="form-control-lg" placeholder="Task Name" id="task-name" required>
            <br>
            Description
            <br>
            <input type="text" class ="form-control-lg" id="description" required>
            <br>
            Assign Member
            <br>
            <select id="members" class="form-control-lg">
              <option disabled>---------</option>
              {% for member in member_list %}
                <option value = "{{member.pk}}"> {{member.username}}</option>
              {% endfor %}
            </select>
          </div>
        <input href="{% url 'task:add_task' id=team_id %}" id="assign-task" class="btn btn-secondary addTask" type="submit" value="Add Task">
      </form>
  </div>
{% endblock %}
{% block scripts %}
<script> 
$(document).ready(function () {
    $("#assign-task").click(function(){
        var task_name = $("#task-name").val()
        var description = $("#description").val()
        var member = $("#members").val()
        if(task_name != "" && description != "" && member != null) {
            $.ajax ({
                method : 'POST',
                url : "{% url 'task:add_task' id=team_id %}",
                dataType : 'json',
                headers: { "X-CSRFToken": Cookies.get("csrftoken") },
                data : {
                    task_name : task_name,
                    description : description,
                    member : member,
                },
                success: function() {
                    window.location.assign("{% url 'dashM:manager' id=team_id %}")
                },
                error: function(){
                    alert("Try again")
                },
            })
        } 
    })
    $("#task-name").keypress(function() {
        $(this).css("background-color","#212a37");
        $(this).css("color","white");
        $("#description").css("background-color","white");
        $("#description").css("color","black");
    });

    $("#description").keypress(function() {
        $(this).css("background-color","#212a37");
        $(this).css("color","white");
        $("#task-name").css("background-color","white");
        $("#task-name").css("color","black");
    });
    $("#members").click(function(){
        $("#task-name").css("background-color","white");
        $("#task-name").css("color","black");
        $("#description").css("background-color","white");
        $("#description").css("color","black");
    })
  })
</script>
{% endblock %}