account/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'acc'
urlpatterns = [
    path('', views.loginPage, name = 'loginPage'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.register, name = 'register'),
    path('validate_username/<str:username>', views.validate_username, name='validate_username'),
]

tk1/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

from .views import index

# views
from team import views as team_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name = 'index'),
    path('login/',include('account.urls')),
    path('dashboard/', team_views.dashboard),
    # path('task/', include('task.urls')),
    path('', index, name = 'home'),
    path('teams/', team_views.dashboard, name='teams'),
    path('create-team/', team_views.create_team, name='create-team'),
    path('delete-team/<int:pk>/', team_views.delete_team, name='delete-team'),
    path('ajax-add-team/', team_views.add_team, name='ajax-add-team'),
    path('login/',include('account.urls', namespace='auth')),
    path('team/<int:id>/task/', include('task.urls', namespace="team")),
    path('team/<int:id>/chat/', include('chat.urls', namespace='chat')),
    path('dashM/<int:id>/', include('dashM.urls', namespace='manager'))
]

account/models.py
from django.db import models

# Create your models here.

account/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreatUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email' , 'password1', 'password2']
       

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from .forms import CreatUserForm
from django.contrib import messages
from django.http import JsonResponse
import json
from django.contrib.auth.models import User
from django.http import HttpResponse

def register(request):
    form = CreatUserForm()
    if request.method == 'POST':
        form = CreatUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('auth:loginPage')

    context ={'form':form}
    return render(request,'register/register.html' , context)

def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('teams')
        else:
            messages.error(request, 'Username or password is incorrect')
            return redirect('auth:loginPage')

    return render(request,'login/login.html')

def logoutUser(request):
    logout(request)
    return redirect('auth:loginPage')

def validate_username(request, username):
    data = {
        'is_taken': User.objects.filter(username=username).exists()
    }
    return JsonResponse(data)

account/templates/login/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;800&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'account/acc/acco.css' %}">

    <title>login</title>
  </head>
  <body>
    <div class="main">
      <div class="container">
        <div class="signup-content">
          <div class="login-img">
            <img id="a" src="{%static 'account/login/Group 13.svg'%}" alt="">
            <img id="rr" src="{%static 'account/login/Group 14.svg'%}" alt="">
            <img  id="b"src="{%static 'account/login/Group 15.svg'%}" alt="">
            <img  id="c"src="{%static 'account/login/Group 16.svg'%}" alt="">
          </div>

          <div class="signup-form">
            <form method="POST" class="register-form">
              {%csrf_token%}
              <div class="form-group">
                <img id="logo" src="{%static 'account/login/ROMUSHA.svg'%}" alt="">
                {% for message in messages %}
                  {% if message.tags == 'success' %}
                    <div style="color:green;" role="alert">
                      {{ message }}
                    </div>
                  {% endif %}
                  {% if message.tags == 'error' %}
                    <div style="color:red;" role="alert">
                      {{ message }}
                    </div>
                  {% endif %}
                {% endfor %}
                  <label for="name">Username</label>
                  <input name ="username" type="username" placeholder=""/>
              </div>
                  
              <div class="form-group">
                  <label for="name">Password</label>
                  <input name ="password" type="password" placeholder=""/>
              </div>

              <div class="form-submit">
                <input type="submit" value="Login" class="submit"/>
              </div>

              <div class="form-submit" style="margin:0;">
                <a id="lo" href="{% url 'acc:register'%}">Sign up</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"crossorigin="anonymous"></script> 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src= "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"> </script>
    <script src= "https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"> </script>
  </body>
</html>