dashM/urls.py
from django.urls import path
from . import views

app_name = "dashM"

urlpatterns = [
	path('', views.dashboard, name = 'manager'),
	path('accept/', views.task_accept_ajax, name='task_accept'),
	path('reject/', views.task_reject_ajax, name='task_reject'),
	path('delete/', views.task_delete_ajax, name='task_delete')
]

task/urls.py
from django.urls import path
from . import views

app_name = 'task'
urlpatterns = [
    path('employee/', views.show_task, name = 'employee'),
    path('add/', views.add_task, name='add_task'),
    path('employee/submit/<int:pk>', views.submit_task, name='submit_task')
]

tk1/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

from .views import index

# views
from team import views as team_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name = 'index'),
    path('login/',include('account.urls')),
    path('dashboard/', team_views.dashboard),
    # path('task/', include('task.urls')),
    path('', index, name = 'home'),
    path('teams/', team_views.dashboard, name='teams'),
    path('create-team/', team_views.create_team, name='create-team'),
    path('delete-team/<int:pk>/', team_views.delete_team, name='delete-team'),
    path('ajax-add-team/', team_views.add_team, name='ajax-add-team'),
    path('login/',include('account.urls', namespace='auth')),
    path('team/<int:id>/task/', include('task.urls', namespace="team")),
    path('team/<int:id>/chat/', include('chat.urls', namespace='chat')),
    path('dashM/<int:id>/', include('dashM.urls', namespace='manager'))
]

team/models.py
# Django Imports
from django.db import models

# Models
from django.contrib.auth.models import User

class Team(models.Model):
  team_owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owned_teams')
  name = models.CharField(max_length=128)
  description = models.TextField()
  members = models.ManyToManyField(User)

  def __str__(self):
    return f'{self.name} is a team owned by {self.team_owner}'

# How to interact with the Team model

# 1. Create Team:
#   team_instance = Team(team_owner=user, name='name', description='description')
#   team_instance.save()

# 2. Add Member:
#   team_instance.members.add(user)

# 3. Check all team members:
#   team_instance.members.all()

# 4. Check all teams owned by user:
#   user.owned_teams.all()

# 5. Check all teams that user is a member of:
#   user.team_set.all()


team/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseBadRequest, HttpResponseForbidden, HttpResponseNotAllowed
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required

# Models
from django.contrib.auth.models import User
from .models import Team

@login_required
def dashboard(request):
  return render(request, 'team/myteams.html')

@login_required
def create_team(request):
  context={
    'users': User.objects.exclude(pk=request.user.pk)
  }
  return render(request, 'team/create-team.html', context)

# Handle team creation using ajax
# Returns JSON
@login_required
def add_team(request):
  if request.method == 'POST':
    try:
      name = request.POST['name']
      description = request.POST['description']
      members = request.POST.getlist('members[]')
    except KeyError:
      return HttpResponseBadRequest

    # Create instance
    new_team = Team(team_owner=request.user, name=name, description=description)
    new_team.save()
    for id in members:
      new_team.members.add(int(id))

    return JsonResponse({
      'success': True
    })
  else:
    return HttpResponseNotAllowed(permitted_methods=['POST'])


@login_required
def delete_team(request, pk):
  try:
    team = Team.objects.get(pk=pk)
  except Team.DoesNotExist:
    return HttpResponseBadRequest

  if (team.team_owner == request.user):
    team.delete()
    return redirect('teams')
  else:
    return HttpResponseForbidden

team/templates/team/create-team.html
{% extends 'base.html' %}
{% load static %}
{% block extra_headers %}
  <link rel="stylesheet" href="/static/team/create-team.css">
{% endblock %}
{% block body %}
<main>
  <div class="scroll-container">
    <div class="top">
      <h1 class="header">CREATE NEW TEAM</h1>
    </div>

    <!-- Warning message -->
    <div class="alert alert-danger mb-3" role="alert">
      Form is not complete
    </div>

    <div class="bottom">
      <div class="illustrations">
        <img src="{% static 'team/illustration-1.svg' %}" alt="">
        <img src="{% static 'team/illustration-2.svg' %}" alt="">
        <img src="{% static 'team/illustration-3.svg' %}" alt="">
      </div>
      <form action="">
        <h4>Team Name</h4>
        <input type="text" name="name" class="form-input" placeholder="Insert team name">
        <h4>Description</h4>
        <input type="text" name="description" class="form-input" placeholder="Insert description">
        <h4>Add Members</h4>
        <small id='member-counter'></small>
        <div class="select-members">
          {% for user in users %}
            <div class="select-items">
              <input class="select-checkbox" type="checkbox" value="{{ user.pk }}">
              <h2>{{ user.username }}</h2>
            </div>
          {% endfor %}
        </div>
        <button id="create-team-btn">Create Team</button>
      </form>
    </div>
  </div>
</main>
{% endblock %}
{% block scripts %}
  <script>
    const data = {
      name: null,
      description: null,
      members: []
    }

    $(document).ready(() => {
      // Initialize content
      const memberCounter = $('#member-counter')
      memberCounter.html(`${data.members.length} members chosen`)

      $('.alert-danger').hide()

      // Handle focus event
      const requiredReminder = $("<div class='required-reminder'><small>This field is required</small></div>")
      $('input').focusin(() => {
        $(requiredReminder).insertBefore($('.form-input:focus'))
      })

      $('input').focusout(() => {
        requiredReminder.remove()
      })

      // Handle change event
      $('input').change(e => {
        data[e.target.name] = e.target.value
        memberCounter.html(`${data.members.length} members chosen`)
      })

      // Handle click event
      $('.select-checkbox').click(e => {
        const id = e.target.value
        const pos = data.members.indexOf(id)
        if (pos !== - 1) {
          data.members.splice(pos, 1)
        } else {
          data.members.push(id)
        }
        console.log(data.members)
      })

      // Handle click event
      $('#create-team-btn').click(e => {
        e.preventDefault()
        let valid_form = true;

        Object.values(data).map(item => {
          if (item === null || item.length === 0) {
            valid_form = false;
          }
        })

        // Send data via ajax
        if (valid_form) {
          $.ajax({
            url: "{% url 'ajax-add-team' %}",
            method : "post",
            dataType : "json",
            data : data,
            headers: { "X-CSRFToken": getCookie("csrftoken") },
            success: (res) => {
              window.location.assign("{% url 'teams' %}")
            },
            error: (res) => {
              alert('Team creation failed')
            }
          })
        } else {
          $('.alert-danger').show()
        }
      })
    })

    function getCookie(c_name)
    {
        if (document.cookie.length > 0)
        {
            c_start = document.cookie.indexOf(c_name + "=");
            if (c_start != -1)
            {
                c_start = c_start + c_name.length + 1;
                c_end = document.cookie.indexOf(";", c_start);
                if (c_end == -1) c_end = document.cookie.length;
                return unescape(document.cookie.substring(c_start,c_end));
            }
        }
        return "";
    }
  </script>
{% endblock %}

team/templates/team/myteams.html
{% extends 'base.html' %}
{% block extra_headers %}
  <link rel="stylesheet" href="/static/team/team.css">
{% endblock %}
{% block body %}
<main class="dashboard">
  <div class="top">
    <a href="{% url 'create-team' %}" id="create-team-btn">Create Team</a>
    <h1 class="title">My Teams</h1>
  </div>
  <div class="bottom">
    <div class="scroll-container">

      <!-- List of owned teams -->
      <div class="owned-teams">
        <h5>Teams I own</h5>
        {% if user.owned_teams.all|length == 0 %}
        <div class="alert alert-primary" role="alert">
          You don't own any teams
        </div>
        {% endif %}
        <div class="team-container">
          {% for team in user.owned_teams.all %}
            <a class="team" href="{% url 'manager:manager' team.pk %}">
              <div>
                <h1 class="team-name">{{ team.name }}</h1>
                <p class="team-desc">{{ team.description }}</p>
              </div>

                <div class="members">
                  {% for member in team.members.all %}
                    <div class="member-item">
                      <h6>{{ member.username|slice:"0:1" }}</h6>
                    </div>
                  {% endfor %}
                </div>
            </a>
          {% endfor %}
        </div>
      </div>

      <!-- List of non-owned teams -->
      <div class="other-teams">
        <h5>Teams I'm a member of</h5>
        {% if user.team_set.all|length == 0 %}
        <div class="alert alert-primary" role="alert">
          You aren't a member of any team
        </div>
        {% endif %}
        <div class="team-container">
          {% for team in user.team_set.all %}
            <a class="team" href="{% url 'team:employee' team.pk %}">
              <div>
                <h1 class="team-name">{{ team.name }}</h1>
                <p class="team-desc">{{ team.description }}</p>
              </div>

              <div class="members">
                {% for member in team.members.all %}
                  <div class="member-item">
                    <h6>{{ member.username|slice:"0:1" }}</h6>
                  </div>
                {% endfor %}
              </div>
            </a>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}