account/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'acc'
urlpatterns = [
    path('', views.loginPage, name = 'loginPage'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.register, name = 'register'),
    path('validate_username/<str:username>', views.validate_username, name='validate_username'),
]

tk1/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

from .views import index

# views
from team import views as team_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name = 'index'),
    path('login/',include('account.urls')),
    path('dashboard/', team_views.dashboard),
    # path('task/', include('task.urls')),
    path('', index, name = 'home'),
    path('teams/', team_views.dashboard, name='teams'),
    path('create-team/', team_views.create_team, name='create-team'),
    path('delete-team/<int:pk>/', team_views.delete_team, name='delete-team'),
    path('ajax-add-team/', team_views.add_team, name='ajax-add-team'),
    path('login/',include('account.urls', namespace='auth')),
    path('team/<int:id>/task/', include('task.urls', namespace="team")),
    path('team/<int:id>/chat/', include('chat.urls', namespace='chat')),
    path('dashM/<int:id>/', include('dashM.urls', namespace='manager'))
]

templates/arrow.html
<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="451.847px" height="451.847px" viewBox="0 0 451.847 451.847" style="enable-background:new 0 0 451.847 451.847;"
	 xml:space="preserve">
<g>
	<path d="M225.923,354.706c-8.098,0-16.195-3.092-22.369-9.263L9.27,151.157c-12.359-12.359-12.359-32.397,0-44.751
		c12.354-12.354,32.388-12.354,44.748,0l171.905,171.915l171.906-171.909c12.359-12.354,32.391-12.354,44.744,0
		c12.365,12.354,12.365,32.392,0,44.751L248.292,345.449C242.115,351.621,234.018,354.706,225.923,354.706z"/>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
</svg>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;800&display=swap" rel="stylesheet">

  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

  <!-- CSS -->
  <link rel="stylesheet" href="{% static 'main.css' %}">

  <!-- Custom Headers -->
  {% block extra_headers %}
  {% endblock %}
</head>
<body>
  <!-- Sidebar -->
  <div class='sidebar'>
    <div class="top">
      <div id="close-container">
        <img id="close-btn" src="{% static 'cross.svg' %}" alt="">
      </div>
      <div class="header">
        <div class="user-initial">
          <h6>{{ user.username|slice:"0:1" }}</h6>
        </div>
        <div class="user-name">{{ user.username }}</div>
      </div>
      <div class="item-container">
        <a href="{% url 'teams' %}" class="item">My Teams</a>
        <a class="chat-head item">
          Chats
          {% include 'arrow.html' %}
        </a>
        <div class="chat-dropdown">
          {% for team in user.owned_teams.all %}
            <a href="{% url 'chat:index' id=team.id %}" class="">{{team.name}}</a>
          {% endfor %}
          {% for team in user.team_set.all %}
            <a href="{% url 'chat:index' id=team.id %}" class="">{{team.name}}</a>
          {% endfor %}
        </div>
        </div>
    </div>
    <div class="footer">
      <a href="{% url 'auth:logout' %}" class="logout-btn">Logout</a>
    </div>
  </div>

  <div class="root">
    <!-- Navbar -->
    <nav>
      <div class="burger">
        <div></div>
        <div></div>
        <div></div>
      </div>
      <div class="content"></div>
    </nav>
    {% block body %}
    {% endblock %}
  </div>
</body>
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script>
  // Sidebar logic
  $(document).ready(() => {
    $('.burger').click(() => {
      $('.sidebar').addClass('show')
    })

    $('#close-btn').click(() => {
      $('.sidebar').removeClass('show')
    })

    $('.chat-head').click(() => {
      $('.chat-dropdown').toggleClass('show')
      $('svg').toggleClass('rotate')
    })
  })
</script>
{% block scripts %}
{% endblock %}
</html>